server:
  port: 7002
  servlet:
    context-path: /ad-binlog-kafka

spring:
  application:
    name: eureka-client-ad-binlog-kafka
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://192.168.150.130:3386/imooc_ad_data?autoReconnect=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2
  kafka:
    bootstrap-servers: 192.168.150.130:9092
    listener:
      concurrency: 4

eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/

adconf:
  mysql:
    host: 192.168.150.130
    port: 3386
    username: root
    password: root
    # binlogName: binlog.000038
    #position: 60451
    binlogName: ""
    position: -1

  kafka:
    topic: ad-search-mysql-data
